Browser("Browser").Page("Page").Link("Login").Click @@ hightlight id_;_Browser("Browser").Page("Page").Link("Login")_;_script infofile_;_ZIP::ssf1.xml_;_
Browser("Browser").Page("Broadleaf Commerce Demo").WebEdit("username").Set "mohsina1zaman@gmail.com" @@ hightlight id_;_Browser("Browser").Page("Broadleaf Commerce Demo").WebEdit("username")_;_script infofile_;_ZIP::ssf2.xml_;_
Browser("Browser").Page("Broadleaf Commerce Demo").WebEdit("password").SetSecure "539a855060bd9175f4d374a5d0b2ee16eeef4c2b769838e508eedaeead9402ef99c6a3d6be64a900a39a" @@ hightlight id_;_Browser("Browser").Page("Broadleaf Commerce Demo").WebEdit("password")_;_script infofile_;_ZIP::ssf3.xml_;_
Browser("Browser").Page("Broadleaf Commerce Demo").WebButton("Login").Click @@ hightlight id_;_Browser("Browser").Page("Broadleaf Commerce Demo").WebButton("Login")_;_script infofile_;_ZIP::ssf4.xml_;_
Browser("Browser").Page("Page").Link("info_outline Out of Stock").Click @@ hightlight id_;_Browser("Browser").Page("Page").Link("info outline Out of Stock")_;_script infofile_;_ZIP::ssf5.xml_;_
Browser("Browser").Page("Sudden Death Sauce - Hot").Link("Receive Inventory Notification").Click @@ hightlight id_;_Browser("Browser").Page("Sudden Death Sauce - Hot").Link("Receive Inventory Notification")_;_script infofile_;_ZIP::ssf6.xml_;_
Browser("Browser").Page("Sudden Death Sauce - Hot").Image("The Heat Clinic Home").Click @@ hightlight id_;_Browser("Browser").Page("Sudden Death Sauce - Hot").Image("The Heat Clinic Home")_;_script infofile_;_ZIP::ssf7.xml_;_
Browser("Browser").Page("Page").Link("info_outline Out of Stock_2").Click @@ hightlight id_;_Browser("Browser").Page("Page").Link("info outline Out of Stock 2")_;_script infofile_;_ZIP::ssf8.xml_;_
Browser("Browser").Page("Green Ghost - Hot Sauces").WebButton("Add to Cart").Click @@ hightlight id_;_Browser("Browser").Page("Green Ghost - Hot Sauces").WebButton("Add to Cart")_;_script infofile_;_ZIP::ssf9.xml_;_
Browser("Browser").Page("Broadleaf Commerce Demo_2").Link("Checkout keyboard_arrow_right").Click @@ hightlight id_;_Browser("Browser").Page("Broadleaf Commerce Demo 2").Link("Checkout keyboard arrow right")_;_script infofile_;_ZIP::ssf10.xml_;_
Browser("Browser").Page("Broadleaf Commerce Demo_3").WebElement("Checkout").Check CheckPoint("Checkout") @@ hightlight id_;_Browser("Browser").Page("Broadleaf Commerce Demo 3").WebElement("Checkout")_;_script infofile_;_ZIP::ssf11.xml_;_
Browser("Browser").Page("Broadleaf Commerce Demo_3").Check CheckPoint("Broadleaf Commerce Demo Store - Heat Clinic - Checkout") @@ hightlight id_;_Browser("Browser").Page("Broadleaf Commerce Demo_3")_;_script infofile_;_ZIP::ssf12.xml_;_
Browser("Browser").Page("Broadleaf Commerce Demo_3").Link("Continue keyboard_arrow_right").Check CheckPoint("Continue keyboard_arrow_right") @@ hightlight id_;_Browser("Browser").Page("Broadleaf Commerce Demo 3").Link("Continue keyboard arrow right")_;_script infofile_;_ZIP::ssf13.xml_;_
Browser("Browser").Page("Broadleaf Commerce Demo_3").Sync @@ hightlight id_;_Browser("Browser").Page("Broadleaf Commerce Demo_3")_;_script infofile_;_ZIP::ssf14.xml_;_
Browser("Browser").CloseAllTabs